info:
  app:
    name: exercise
    version: 1.0.0-SNAPSHOT
    description:  exercise

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.byung8.fitness.exercise.mapper
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
spring:
  profiles:
    active: local
---
spring:
  profiles: prod
  pid:
    file: /exercise/run/exercise.pid
  datasource:
    url: jdbc:mysql://${DB_URI}/fitness?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:logback-prod.xml
log:
  file:
    path: "/exercise/logs"
server:
  port: 8080
  tomcat:
    accesslog:
      prefix: access-log
      suffix: log
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "/exercise"
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profiles: local
  pid:
    file: C://dev/work/fitness/exercise/run/exercise.pid
  datasource:
    url: jdbc:mysql://192.168.0.111:30268/fitness?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: byung8
    password: 1q2w3e4r5t
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:logback-local.xml
log:
  file:
    path: "C://dev/work/fitness/exercise/logs"
server:
  port: 8080
  tomcat:
    accesslog:
      rotate: true      
      encoding: UTF-8
      pattern: "%h %l %u [%t] \"%m %U %H\" %s %b %D"
      enabled: true
    basedir: "C://dev/work/fitness/exercise"
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
 